import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/stores/tost/ToastProvider";

const monts = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={monts.className}>
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
